-- local nvim_test = require('nvim-test')
-- local Runner = require "nvim-test.runner"
--
-- local mix_test = Runner:init({
--   command = "mix test",
--   file_pattern = "\\v(test_[^.]+|[^.]+_test|tests)\\.exs$",
--   find_files = { "{name}_test.exs", "tests.exs", "tests" },
-- }, {
--   python = [[
--       ; Class
--       (
--         (
--           class_definition name: (identifier) @test-name
--           (#match? @test-name "[Tt]est")
--         )
--       @scope-root)
--
--       ; Function
--       (
--         (
--           function_definition name: (identifier) @test-name
--           (#match? @test-name "^[Tt]est")
--         )
--       @scope-root)
--     ]],
-- })
--
-- function mix_test:build_test_args(args, tests)
--   args[#args] = args[#args] .. "::" .. table.concat(tests, "::")
-- end
--
-- require('nvim-test').setup {
--   run = true,                 -- run tests (using for debug)
--   commands_create = true,     -- create commands (TestFile, TestLast, ...)
--   filename_modifier = ":.",   -- modify filenames before tests run(:h filename-modifiers)
--   silent = false,             -- less notifications
--   term = "terminal",          -- a terminal to run ("terminal"|"toggleterm")
--   termOpts = {
--     direction = "vertical",   -- terminal's direction ("horizontal"|"vertical"|"float")
--     width = 96,               -- terminal's width (for vertical|float)
--     height = 24,              -- terminal's height (for horizontal|float)
--     go_back = false,          -- return focus to original window after executing
--     stopinsert = "auto",      -- exit from insert mode (true|false|"auto")
--     keep_one = true,          -- keep only one terminal for testing
--   },
--   runners = {               -- setup tests runners
--     cs = "nvim-test.runners.dotnet",
--     go = "nvim-test.runners.go-test",
--     haskell = "nvim-test.runners.hspec",
--     javascriptreact = "nvim-test.runners.jest",
--     javascript = "nvim-test.runners.jest",
--     lua = "nvim-test.runners.busted",
--     python = "nvim-test.runners.pytest",
--     ruby = "nvim-test.runners.rspec",
--     rust = "nvim-test.runners.cargo-test",
--     typescript = "nvim-test.runners.jest",
--     typescriptreact = "nvim-test.runners.jest",
--     elixir = mix_test,
--   }
-- }
